package com.project.UI;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.project.dictManagement.*;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.*;
import java.util.Locale;

public class addWord extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JTextField textFieldAddPronounce;
    private JTextField textFieldAddWord;
    private JPanel panelWord;
    private JLabel labelWord;
    private JPanel panelPronounce;
    private JLabel labelPronounce;
    private JPanel panelNewDefinition;
    private JLabel labelDefinition;
    private JPanel panelWordPronounce;
    private JEditorPane editorPaneAddDefinition;

    public addWord() {
        setContentPane(contentPane);
        setModal(true);
        //getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(e -> onOK());

        buttonCancel.addActionListener(e -> onCancel());

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(e -> onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

    }

    private void onOK() {
        int confirm = JOptionPane.showConfirmDialog(contentPane, "This action will make the database change!\n" +
                "Are you sure about adding this word to dictionary?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (!DictionaryCommandline.insertWord(textFieldAddWord.getText(), textFieldAddPronounce.getText()
                    , editorPaneAddDefinition.getText())) {
                JOptionPane.showMessageDialog(contentPane,
                        "Word\"" + textFieldAddWord.getText() + "\"" + "is existed!");
            } else {
                JOptionPane.showMessageDialog(contentPane,
                        "Word\"" + textFieldAddWord.getText() + "\"" + "was added successfully!");
            }
            dispose();
        }
    }

    private void onCancel() {
        // add your code here if necessary
        dispose();
    }


    public static void main(String[] args) {
        addWord dialog = new addWord();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        System.exit(0);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
        contentPane.setBackground(new Color(-11711155));
        contentPane.setPreferredSize(new Dimension(640, 480));
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-11711155)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        panel2.setAutoscrolls(false);
        panel2.setBackground(new Color(-12559704));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-1)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        buttonOK = new JButton();
        buttonOK.setBackground(new Color(-9805144));
        Font buttonOKFont = this.$$$getFont$$$("Consolas", -1, 18, buttonOK.getFont());
        if (buttonOKFont != null) buttonOK.setFont(buttonOKFont);
        buttonOK.setForeground(new Color(-4397831));
        buttonOK.setHideActionText(false);
        buttonOK.setText("OK");
        panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setBackground(new Color(-9805144));
        Font buttonCancelFont = this.$$$getFont$$$("Consolas", -1, 18, buttonCancel.getFont());
        if (buttonCancelFont != null) buttonCancel.setFont(buttonCancelFont);
        buttonCancel.setForeground(new Color(-4397831));
        buttonCancel.setText("Cancel");
        panel2.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelWordPronounce = new JPanel();
        panelWordPronounce.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelWordPronounce.setBackground(new Color(-12559704));
        contentPane.add(panelWordPronounce, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelWordPronounce.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-1)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        panelWord = new JPanel();
        panelWord.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelWord.setBackground(new Color(-12559704));
        panelWordPronounce.add(panelWord, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelWord.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-12559704)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-1)));
        labelWord = new JLabel();
        Font labelWordFont = this.$$$getFont$$$("Consolas", -1, 18, labelWord.getFont());
        if (labelWordFont != null) labelWord.setFont(labelWordFont);
        labelWord.setForeground(new Color(-4397831));
        labelWord.setText("New word: ");
        panelWord.add(labelWord, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldAddWord = new JTextField();
        textFieldAddWord.setBackground(new Color(-11711155));
        textFieldAddWord.setCaretColor(new Color(-21419));
        Font textFieldAddWordFont = this.$$$getFont$$$("Consolas", -1, 18, textFieldAddWord.getFont());
        if (textFieldAddWordFont != null) textFieldAddWord.setFont(textFieldAddWordFont);
        textFieldAddWord.setForeground(new Color(-4397831));
        textFieldAddWord.setSelectedTextColor(new Color(-12559704));
        textFieldAddWord.setSelectionColor(new Color(-4397831));
        textFieldAddWord.setText("");
        panelWord.add(textFieldAddWord, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panelPronounce = new JPanel();
        panelPronounce.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelPronounce.setBackground(new Color(-12559704));
        panelWordPronounce.add(panelPronounce, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelPronounce.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-12559704)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-1)));
        labelPronounce = new JLabel();
        Font labelPronounceFont = this.$$$getFont$$$("Consolas", -1, 18, labelPronounce.getFont());
        if (labelPronounceFont != null) labelPronounce.setFont(labelPronounceFont);
        labelPronounce.setForeground(new Color(-4397831));
        labelPronounce.setText("Pronounciation:");
        panelPronounce.add(labelPronounce, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldAddPronounce = new JTextField();
        textFieldAddPronounce.setBackground(new Color(-11711155));
        textFieldAddPronounce.setCaretColor(new Color(-21419));
        Font textFieldAddPronounceFont = this.$$$getFont$$$("Consolas", -1, 18, textFieldAddPronounce.getFont());
        if (textFieldAddPronounceFont != null) textFieldAddPronounce.setFont(textFieldAddPronounceFont);
        textFieldAddPronounce.setForeground(new Color(-4397831));
        textFieldAddPronounce.setSelectedTextColor(new Color(-12559704));
        textFieldAddPronounce.setSelectionColor(new Color(-4397831));
        panelPronounce.add(textFieldAddPronounce, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panelNewDefinition = new JPanel();
        panelNewDefinition.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelNewDefinition.setBackground(new Color(-12559704));
        contentPane.add(panelNewDefinition, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelNewDefinition.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-1)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        labelDefinition = new JLabel();
        labelDefinition.setBackground(new Color(-4397831));
        Font labelDefinitionFont = this.$$$getFont$$$("Consolas", -1, 18, labelDefinition.getFont());
        if (labelDefinitionFont != null) labelDefinition.setFont(labelDefinitionFont);
        labelDefinition.setForeground(new Color(-4397831));
        labelDefinition.setText("Definition:");
        panelNewDefinition.add(labelDefinition, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        editorPaneAddDefinition = new JEditorPane();
        editorPaneAddDefinition.setAutoscrolls(true);
        editorPaneAddDefinition.setBackground(new Color(-11711155));
        editorPaneAddDefinition.setCaretColor(new Color(-21419));
        Font editorPaneAddDefinitionFont = this.$$$getFont$$$("Consolas", -1, 18, editorPaneAddDefinition.getFont());
        if (editorPaneAddDefinitionFont != null) editorPaneAddDefinition.setFont(editorPaneAddDefinitionFont);
        editorPaneAddDefinition.setForeground(new Color(-4397831));
        panelNewDefinition.add(editorPaneAddDefinition, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
